# ===================================================================
# Configuration.
#
# This configuration will be overridden by the BACKEND_ENV you use,
# for example application-dev.yml if you use the "dev" profile.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Standard app properties.
# ===================================================================

eureka:
    client:
        enabled: false
        healthcheck:
            enabled: true
        fetch-registry: true
        register-with-eureka: true
        instance-info-replication-interval-seconds: 10
        registry-fetch-interval-seconds: 10
    instance:
        appname: gen
        instanceId: gen:${random.value}
        lease-renewal-interval-in-seconds: 5
        lease-expiration-duration-in-seconds: 10
        status-page-url-path: ${management.endpoints.web.base-path}/info
        health-check-url-path: ${management.endpoints.web.base-path}/health
        metadata-map:
            zone: primary # This is needed for the load balancer
            version: #project.version#
            git-version: ${git.commit.id.describe:}
            git-commit: ${git.commit.id.abbrev:}
            git-branch: ${git.branch:}

# ===================================================================
# JHipster specific properties
#
# Full reference is available at: https://www.jhipster.tech/common-application-properties/
# ===================================================================

jhipster:
    clientApp:
        name: 'gen'
    registry:
        password: admin
    security:
        session:
            secret: 'gen session secret'
        oauth2:
            client:
                provider:
                    oidc:
                        issuer-uri: http://localhost:9080/auth/realms/jhipster
                registration:
                    oidc:
                        client-id: web_app
                        client-secret: web_app
    mail:
        from: gen@localhost
    swagger:
        default-include-pattern: /api/.*
        title: gen API
        description: gen API documentation
        version: 0.0.1
        terms-of-service-url:
        contact-name:
        contact-url:
        contact-email:
        license:
        license-url:
        path: /api/v2/api-docs

cloud:
    config:
        uri: http://admin:${jhipster.registry.password}@localhost:8761/config
        # name of the config server's property source (file.yml) that we want to use
        name: gen
        profile: prod # profile(s) of the property source
        label: master # toggle to switch to a different version of the configuration as stored in git
        # it can be set to any label, branch or commit of the configuration source Git repository
# ===================================================================
# Application specific properties
# Add your own application properties here, see the ApplicationProperties class
# to have type-safe configuration, like in the JHipsterProperties above
#
# More documentation is available at:
# https://www.jhipster.tech/common-application-properties/
# ===================================================================

# application:
